@startuml
left to right direction
skinparam componentStyle uml2
title Nastavení front v RabbitMQ


package "vhost: antivir" {
        interface "clamav-check" as CC
        [check] --> CC
        [check-result]
        cloud {
              interface "clamav-check-consument-01" as Cons_CC_01
              interface "clamav-check-consument-02" as Cons_CC_02
              interface "clamav-check-consument-03" as Cons_CC_03
              CC ..> Cons_CC_01
              CC ..> Cons_CC_02
              CC ..> Cons_CC_03
              Cons_CC_01 ---> [check-result]
              Cons_CC_02 ---> [check-result]
              Cons_CC_03 ---> [check-result]
        }
}

package "vhost: pdf" {
        interface "pdfbox-validate" as PDFBOX_VAL
        interface "pdfbox-validate-extract-metadata" as PDFBOX_VAL_META
        interface "pdfbox-extract-metadata" as PDFBOX_META

        [validate]
        [validate and extract metadata]
        [extract metadata]
        [validators-result]

        [validate] --> PDFBOX_VAL
        [validate and extract metadata] --> PDFBOX_VAL_META
        [extract metadata] --> PDFBOX_META

        cloud {
              interface "pdfbox-validate-consument-01" as PDFBOX_VAL_Cons_01
              interface "pdfbox-validate-consument-02" as PDFBOX_VAL_Cons_02
              interface "pdfbox-validate-extract-metadata-consument-01" as PDFBOX_VAL_META_Cons_01
              interface "pdfbox-validate-extract-metadata-consument-02" as PDFBOX_VAL_META_Cons_02
              interface "pdfbox-extract-metadata-consument-01" as PDFBOX_META_Cons_01
              interface "pdfbox-extract-metadata-consument-02" as PDFBOX_META_Cons_02

              PDFBOX_VAL ..> PDFBOX_VAL_Cons_01
              PDFBOX_VAL ..> PDFBOX_VAL_Cons_02

              PDFBOX_VAL_META ..> PDFBOX_VAL_META_Cons_01
              PDFBOX_VAL_META ..> PDFBOX_VAL_META_Cons_02

              PDFBOX_META ..> PDFBOX_META_Cons_01
              PDFBOX_META ..> PDFBOX_META_Cons_02
              
              PDFBOX_VAL_Cons_01 ---> [validators-result]
              PDFBOX_VAL_Cons_02 ---> [validators-result]
              PDFBOX_VAL_META_Cons_01 ---> [validators-result]
              PDFBOX_VAL_META_Cons_02 ---> [validators-result]
              PDFBOX_META_Cons_01 ---> [validators-result]
              PDFBOX_META_Cons_02 ---> [validators-result]
        }
}

package "vhost: edeposit" {
        [epublication-submitted]
        [eperiodical-submitted]
        [book-submitted]
}

package "vhost: aleph" {
        [search]
        [search-response]
}

@enduml