@startuml
skinparam componentStyle uml2
left to right direction
title Základní datový model pro komunikaci s AMQP

package edeposit.amqp.types {
enum TypeOfSerialization {
     JSON
     BSON
     XML
     Protobuf
}

enum InterfaceOfData {
     antivir.check
     aleph.search
     pdfbox.validate
     pdfbox.validateAndExtractMetadata
     pdfbox.extractMetadata
     epubcheck.validate
     epubcheck.validateAndExtractMetadata
     epubcheck.extractMetadata
}
}


package edeposit.amqp.interfaces {

interface IAMQPMessage {
          String replyTo
          String contentType
          String deliveryMode
}

Interface IMessage {
      String uuid
      String created
      String interface
      String serialization
      Binary data
}

interface IRequest {
}

interface IResponse {
      String uuidOfRequest
}

IMessage <|-right- IRequest
IMessage <|-left- IResponse
        
        interface IData {
        }       

        interface IDataWithUrl {
              String urlOfFile
        }

        interface IDataWithStream {
              Binary stream
        }

        interface IDataWithValidationResult {
                  Boolean isValid
                  Strings errors
                  String message
        }

        IData <|-right- IDataWithUrl
        IData <|-right- IDataWithStream
        IData <|-right- IDataWithValidationResult
}


IMessage -- IDataWithUrl : < describes an attribute <b>data</b>
IMessage -- IDataWithStream : < describes an attribute <b>data</b>
IMessage -left- TypeOfSerialization : <b>serialization</b> is one of >
IMessage -left- InterfaceOfData : <b>interface</b> is one of >

IMessage -- IDataWithValidationResult : < describes an attribute <b>data</b>

package edeposit.amqp.actors {
        interface ISender {
                send(IMessage message)                            
        }
        note bottom
        Sends a given message to <b>message broker</b>. 
        Implementation knows what exchange in <b>message broker</b> uses.
        end note
        
        interface IDataExecutor {
                  result execute(IData data)
        }
        note bottom
        It handles data from <b>Request</b>
        end note

        interface IRequestExecutor {
                  execute(IRequest request)                  
        }
}

@enduml
