@startuml
skinparam componentStyle uml2
left to right direction
title Datový model pro antivirus

class Request {
      String muuid
      String created
      String interface
      String serialization
      Binary data
}

class MessageWithUrl {
      String urlOfFile
}

class MessageWithStream {
      Binary stream
}

class Response {
      String muuid
      String parent_uuid
      String created
      String interface
      String serialization
      Boolean is_clean
      Boolean include_data
      Binary data
}

class MessageWithResult {
      Boolean contentIsClean
      String info
}

Request *-- MessageWithUrl : is attribute <b>data</b> using serialization
Request *-- MessageWithStream : is attribute <b>data</b> using serialization

Response *-- MessageWithResult : is attribute <b>data</b> using serialization

@enduml
