@startuml
skinparam componentStyle uml2
left to right direction
title Datový model pro PDFBox

package edeposit.amqp.pdfbox.interfaces {
 interface ValidateRequestWithUrl {
           String urlOfFile
 }

 interface ValidateRequestWithStream {
           Binary stream
 }
 
 interface ValidateResponse {
           Boolean isValid
           String info
           Strings errors
 }
 interface ValidateResponseWithMetadata {
           Boolean isValid
           String info
           Strings errors
           Boolean isEncrypted
           String title
           String author
 }
}

@enduml
