@startuml
left to right direction
skinparam componentStyle uml2
title Architektura systému
() "SCP" as SCP
() "AMQP" as AMQP

package "E-Deposit" {
() "HTTP" as HTTP
() "OAI-PMH" as OAIPMH

package "AMQP Middleware" {
[RabbitMQ] ..> AMQP : používá
[RabbitMQ] ..> SCP : používá
}

[RabbitMQ] ..> REST : používá
[Plone] ..> AMQP : používá
[Plone] <---> [RabbitMQ] : posílá zprávy
[Plone] <---> [RabbitMQ] : přijímá zprávy
[Plone] ..> HTTP : používá
[Plone] ..> OAIPMH : poskytuje bránu
[ftp server]
[RabbitMQ] --> [ftp server] : čte příchozí ohlášení
}

package "NKP" {
[smtp server]
[smtp server] --> [imap server] : ukládá příchozí emaily

[imap server]
[RabbitMQ] --> [imap server] : čte nové emaily
[RabbitMQ] --> [imap server] : maže zpracované emaily

[RabbitMQ] --> [Kramerius] : posílá nové epublikace
[Kramerius] ..> REST : používá
[Kramerius] ..> SCP : používá

[RabbitMQ] --> [Aleph] : ptá se na metadata
[RabbitMQ] --> [Aleph] : posílá nové metadata
[Aleph]
}


[Kramerius-01] <--> [Plone]: načítá nové epublikace
[Kramerius-01] ..> OAIPMH: používá

[Kramerius-02] <--> [Plone]: načítá nové epublikace
[Kramerius-02] ..> OAIPMH : používá

package "NDK" {
[RabbitMQ] -down-> [LTP] : posílá nové epublikace
[RabbitMQ] -down-> [LTP] : stahuje soubory epublikace
[LTP]
}

@enduml