@startuml
left to right direction
skinparam componentStyle uml2
title Architektura systému

package "E-Deposit" {
() "HTTP" as HTTP
() "OAI-PMH" as OAIPMH
() "SCP" as SCP
() "AMQP" as AMQP
() "email" as EMAIL

package "AMQP Middleware" {
[RabbitMQ] ..> AMQP : používá
[RabbitMQ] ..> SCP : používá
[RabbitMQ] <---> [Aleph daemon]
[RabbitMQ] <---> [ISBN validator]
[RabbitMQ] <---> [Aleph exporter]
[RabbitMQ] <---> [thumbnail generator]
[RabbitMQ] <---> [file antivirus]
[RabbitMQ] <---> [PDF validator]
[RabbitMQ] <---> [EPUB validator]
[RabbitMQ] <---> [Kramerius exporter]
[RabbitMQ] <---> [LTP exporter]
[RabbitMQ] <---> [IMAP service]
[RabbitMQ] <---> [FTP service]
[RabbitMQ] <---> [Storage service]
[RabbitMQ] <---> [URN:NBN registration]
[RabbitMQ] <---> [PDF generator]
[RabbitMQ] <---> [REST server]
}

[RabbitMQ] ..> REST : používá
[Plone] ..> AMQP : používá
[Plone] <-down-> [RabbitMQ] : posílá zprávy
[Plone] <-down-> [RabbitMQ] : přijímá zprávy
[Plone] ..> HTTP : používá
[Plone] ..> OAIPMH : poskytuje bránu
[Plone] ..> EMAIL: rozesílá emaily
[FTP service] -left-> [ftp server] : čte příchozí ohlášení
[FTP service] -left-> [ftp server] : nastavuje přístupy k účtům
[ftp server]
}

package "NKP" {
[smtp server]
[smtp server] --> [imap server] : ukládá příchozí emaily

[imap server]
[IMAP service] --> [imap server] : čte nové emaily
[IMAP service] --> [imap server] : maže zpracované emaily

[Kramerius exporter] --> [Kramerius] : posílá nové epublikace
[Kramerius] ..> REST : používá
[Kramerius] ..> SCP : používá

[Aleph daemon] --> [Aleph] : ptá se na metadata
[Aleph exporter] --> [Aleph] : posílá nové metadata
[ISBN validator] --> [Aleph] : kontroluje duplicitu ISBN
[Aleph]
[URN:NBN registration] --> [URN:NBN resolver]
}


[Kramerius-01] <--> [Plone]: načítá nové epublikace
[Kramerius-01] ..> OAIPMH: používá

[Kramerius-02] <--> [Plone]: načítá nové epublikace
[Kramerius-02] ..> OAIPMH : používá

package "NDK" {
[LTP exporter] --> [LTP] : posílá nové epublikace
[LTP]
}

@enduml