@startuml
skinparam componentStyle uml2
left to right direction
title Datový model E-publikace

class Library {
      String title
      String url
      String urlOfKramerius
}

class ISBN {
      String ISBN
      boolean isValid()
}

class PreviewFile {
      String format
      File file
}

class OriginalFile {
      String url
      String format
      File file
}

class Author {
      String firstName
      String lastName
}

class PrintingFile {
      String url
      String format
      File file
}

class EPublication {
      String title  "M21:245 $a"
      String subtitle 
      String bookBinding 
      Decimal price 
      String volume
      String volumeTitle
      String volumeNumber
      String edition "M21:490 $a"
      String editionNumber "M21:490 $v"
      String subedition "M21:490 $a"
      String subeditionNumber "M21:490 $v"
      String placeOfPublishing "M21:264 $a"
      String publisher "M21:264 $b"
      Date   dateOfPublishing "M21:264 $c"
      String publishedWithCoedition 
      String publishedAtOrder 
      String personWhoProcessedThis
      Relation librariesThatCanAccessAtLibraryTerminal
      Relation librariesThatCanAccessAtPublic
      String alephDocNumber
      Boolean generateISBN
      String categoryForRIV
      String placeOfDistribution "M21:264 $a"
      String distributor "M21:264 $b"
      Date dateOfDistribution "M21:264 $c"
      String placeOfProduction "M21:264 $a"
      String producer "M21:264 $b"
      Date dateOfProduction "M21:264 $c"
      Date dateOfCopyright "M21:264 $c"
      String development "M21:020 $a"
      String mediaType "M21:338 $a"
}

class EPublicationFolder {
      
}

class LibraryFolder {
}

Library "0..*" -- "0..*" EPublication: canAccessAtLibraryTerminal >
Library "0..*" -- "0..*" EPublication: canAccessAtPublic >
EPublication *-- "0..*" OriginalFile
EPublication *-- "0..*" PrintingFile
EPublication *-- "0..*" Author
EPublication "0..*" *-- "0..*" PreviewFile: main preview files
OriginalFile "0..*" *-- "1..*" ISBN
PrintingFile "0..*" *-- "0..*" ISBN
OriginalFile "0..*" *-- "1..*" PreviewFile
PrintingFile "0..*" *-- "1..*" PreviewFile
EPublicationFolder *-- "0..*" EPublication
LibraryFolder *-- "0..*" Library

@enduml