@startuml
left to right direction
title Datový model Informace o producentovi

class AgreementFile {
      String agreement
}

class ProducentUser {
      String firstName
      String lastName
      String phone
      Boolean accept
}

class Producent {
      String street
      String city
      String country
      String contact
}

class ProducentFolder {
}

class ProducentAdministrator {
}

class ProducentAssistant {
}

ProducentUser <|-- ProducentAdministrator
ProducentUser <|-- ProducentAssistant


Producent "0..*" *-- "0..*" AgreementFile
Producent "0..*" *-- "0..*" User
User "0..1" -- "0..1" Producent
ProducentFolder "0..*" *-- "0..*" Producent

@enduml