@startuml
left to right direction
title Akvizice publikace
skinparam packageStyle rect

actor :Nakladatel/vydavatel: as nakl
actor :Pracovník agentury ISBN: as isbn
actor :Pracovník akvizice: as akv
actor :Systém: as sys
actor :Správce systému Aleph: as aleph
actor :Administrátor akvizice: as admAkv

:isbn: -left-> (Aleph: Kontrola ISBN)
:akv: -left-> (Aleph: Kontrola metadat)

rectangle  {
	   :sys: -left-> (UC03-01 Předání metadat k importu do Aleph)
	   :isbn: -left-> (UC03-02 Kontrola ISBN)
	   :admAkv: -left-> (UC03-03-00 Příprava akvizice)
	   :akv: -left-> (UC03-03 Kontrola metadat)
	   :akv: -left-> (UC03-04 Přijetí e-publikace)
	   :isbn: -left-> (UC03-05 Kontrola ISBN v souboru)
	   :nakl: --> (UC03-06 Oprava souboru)
	   :nakl: --> (UC03-07 Stáhnutí souboru)
	   :akv: --> (UC03-08 Blokování přístupu k e-publikaci)
	   :akv: --> (UC03-09 Odmítnutí e-publikace)
	   :akv: --> (UC03-10 Odstranění duplicity)
	   :akv: --> (UC03-11 Oprava metadat)
	   :nakl: --> (UC02-15 Dodatečná oprava metadat)
}
:akv: -left-> (Aleph: doplnění popisných metadat)
:isbn: -left-> (Aleph: kontrola ISBN)
:isbn: -left-> (Aleph: kontrola ISBN v souborech)
@enduml
