@startuml
title <b>Pracovní cyklus pokračujícího zdroje</b>
skinparam DefaultFontSize 16pt

skinparam state {
  StartColor MediumBlue
  EndColor MediumBlue
  BackgroundColor Peru
  BackgroundColor<< Begin >> Olive
  BorderColor Peru
  FontName Impact
  ArrowColor Green
}

state "Ohlášení" as declaration #SandyBrown
declaration : možnost ohlášení pokračujícího zdroje

state "Akvizice" as acquisition #ECE8DF
state "Příprava akvizice" as acquisitionPreparing #ECE8DF
state "Příprava katalogizace" as catalogizationPreparing #ECE8DF
state "Katalogizace" as catalogization #ECE8DF
state "Oprava" as declarationWithError #SandyBrown
state "Export do Alephu" as exportToAleph #SteelBlue
state "Stažený z oběhu" as withdrawn #ECE8DF

[*] ---> declaration

declaration --> exportToAleph : << producent >> \n << akvizice >> \n K akvizici

exportToAleph ---> acquisitionPreparing : << system >> \n Export to Aleph OK
exportToAleph --> declarationWithError : << system >> \n Export to Aleph Error

acquisitionPreparing ---> acquisition : << správce akvizice >> \n Potvrdit přidělení
acquisition ---> declarationWithError : << akvizice >> \n Vrátit k opravě
acquisition ---> catalogizationPreparing : << akvizice >> \n Potvrdit a ke katalogizaci
acquisition ---> declarationWithError : << producent >> \n Vrátit k opravě
acquisition ---> withdrawn : << akvizice >> \n Stáhnout z oběhu

declarationWithError ---> exportToAleph : << producent >> \n K akvizici
declarationWithError ---> withdrawn : << akvizice >> \n Stáhnout z oběhu

catalogizationPreparing --> catalogization : << administrátor katalogizace >> \n Ke katalogizaci
catalogization ---> declarationWithError : << producent >> \n Vrátit k opravě
catalogization ---> withdrawn : << knihovník >> \n Stáhnout z oběhu

withdrawn ---> [*]
catalogization ---> [*]

@enduml
